gray_whale_quiz = {
    "What is the scientific name of the gray whale?": "Eschrichtius robustus",
    "To which family does the gray whale belong?": "Eschrichtiidae",
    "What is the average length of an adult male gray whale?": "45-46 feet (13.7-14 m)",
    "How much does an adult gray whale typically weigh?": "30-40 tons (27,200-36,300 kg)",
    "How many grooves are found on the ventral throat of a gray whale?": "2-5 grooves",
    "What is the color of newborn gray whale calves?": "Dark gray to black",
    "How many baleen plates does a gray whale have?": "130-180 baleen plates",
    "What is the gestation period for a gray whale?": "12-13 months",
    "How long do gray whale calves nurse?": "7-8 months",
    "What percentage of fat is in gray whale milk?": "53% fat",
    "How often do female gray whales typically give birth?": "At intervals of 2 or more years",
    "What is the average round-trip distance of a gray whale's migration?": "10,000-14,000 miles (16,000-22,530 km) round trip",
    "In which seas do gray whales primarily feed during summer?": "Bering and Chukchi seas",
    "How long can a gray whale stay submerged?": "Up to 15 minutes",
    "What is the current estimated population size of the eastern North Pacific gray whale?": "Between 19,000 and 23,000",
    "Why are gray whales considered 'coastal' whales?": "They migrate along the North American Pacific Coast and inhabit shallow coastal waters of the eastern North Pacific",
    "How does the gray whale's feeding mechanism work?": "Gray whales dive to the bottom, roll on their side, and draw bottom sediments and water into their mouth. As they close their mouth, water and sediments are expelled through the baleen plates, which trap the food on the inside near the tongue to be swallowed",
    "Why do gray whales migrate to Baja California, Mexico?": "For mating and calving in the lagoons",
    "What factors contribute to the unique appearance of gray whales?": "Gray patches and white mottling on their dark skin, scratches, scattered patches of white barnacles, and orange whale lice",
    "How does the gray whale's body structure differ from other whale species?": "Gray whales have no dorsal fin. Instead, they have a prominent dorsal hump followed by a series of 6-12 knuckles along the dorsal ridge",
    "Why is the gray whale's migration considered one of the longest among mammals?": "It averages 10,000-14,000 miles (16,000-22,530 km) round trip",
    "How has commercial whale watching impacted human interaction with gray whales?": "It has become a major industry along the gray whale's migration route, providing unique opportunities for land and boat observation",
    "What is the significance of the 'friendlies' phenomenon in gray whale behavior?": "It refers to gray whales in the calving and breeding lagoons that closely approach small boats and allow themselves to be touched by humans",
    "How has the protection of gray whales affected their population recovery?": "Since receiving full protection in 1947, the eastern North Pacific gray whale population has made a remarkable recovery, now numbering between 19,000 and 23,000, which is probably close to their original population size",
    "Why do mother gray whales and calves travel close to shore during the northbound migration?": "Likely for protection and to allow calves to rest in shallower waters",
    "How does the gray whale's feeding habitat influence its diet?": "Gray whales' feeding habitat in the Arctic waters influences their diet of small crustaceans such as amphipods and tube worms found in bottom sediments",
    "What role do orcas play in the natural history of gray whales?": "Orcas (killer whales) are a cause of gray whale deaths, and many gray whales have orca teeth scars on their flukes",
    "How did early whalers' experiences with gray whales influence their perception of the species?": "Early whalers' experiences with gray whales in the lagoons led them to name the species 'Devilfish' due to the whales' violent defensive behaviors, particularly mothers protecting their calves",
    "Why is the western North Pacific gray whale population currently depleted?": "Possibly due to over-hunting",
    "How has the gray whale population changed since receiving full protection in 1947?": "The eastern North Pacific gray whale population has recovered from near extinction to its current estimated size of 19,000-23,000"
}

__all__ = ['gray_whale_quiz']